name: Build Docker Image Development ARU Api

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/gis:api-develop
    - name: deploy to Vm Aru Staging
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.ARU_HOST }}
        username: root
        password: ${{ secrets.ARU_PASSWORD }}
        port: ${{ secrets.ARU_PORT }}
        script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/aru-app:api-prod
            docker-compose -f /home/devrl/ARU-Backup/docker-compose.yml up -d
    - name: run alert
      run: sh ./alert-api-script.sh
      shell: bash
